web:
 image: pablofmorales/apache-php7
 ports:
  - "8080:80"
  - "8443:443"
 volumes:
  - /Users/marc/site/sometest/BlogMVC/blog:/var/www/html
 links:
  - db:db
db:
 image: mysql
 volumes:
  - /Users/marc/site/sometest/BlogMVC/data:/var/lib/mysql
 environment:
  MYSQL_ROOT_PASSWORD: root